### ISSUE TITLE
KatharsisConfigV2 beans not available.

### ISSUE THREAD

**Issue by coderange** [katharsis-project/katharsis-spring#12]
KatharsisConfig has been deprecated in v2.1.5 and it recommends using KatharsisConfigV2.
The spring example suggests using @Import(KatharsisConfig.class) but this does not work for KatharsisConfigV2 due to the fact that it relies on beans created in other configuration classes that are package-scoped (the ones in the same file as KatharsisConfigV2). It seems natural that spring would pick them up, but it doesn't.

What you have to do to make it work is to use @ComponentScan and pass the package like so :
@ComponentScan(value = {"your.package", "io.katharsis.spring.boot"})

but since this scans the whole package, the scan also picks up KatharsisConfig which lies in the same package. So you need to exclude that :

@ComponentScan(value = {"your.packages.etc.etc", "io.katharsis.spring.boot"},
        excludeFilters = {@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, value = KatharsisConfig.class)})

Then spring picks up KatharsisConfigV2 only.

**Comment by meshuga** [comment]
Sorry, I'll fix that

**Comment by meshuga** [comment]
done in v2.1.7
