### ISSUE TITLE
CORS: KatharsisFilterV2 does NOT allow OPTIONS requests to return a 200

### ISSUE THREAD

**Issue by keithdmoore** [katharsis-project/katharsis-spring#21]
Looks like to satisfy preflight OPTIONS requests, a 200 needs to be returned.  Can this be changed to return a 200 instead of a 204?  Maybe set the content-length to zero and return a 200?

**Comment by iamchrismiller** [comment]
It looks like the Options request requires the header `Accept : application/json` or at least some acceptable Accept header. Without this header in the Options request it returns a  `HttpServletResponse.SC_NO_CONTENT` which is breaking all Cross origin GET requests. The browser is currently sending the default Accept: * and it is failing within `io.katharsis.spring.KatharsisFilterV2`. Has anyone else run into this issue?

**Comment by keithdmoore** [comment]
I managed to get a CorsFilter to run prior to the KatharsisFilterV2.  So now it's just a matter of having a 200 returned in the case of an OPTIONS request.

**Comment by keithdmoore** [comment]
In KatharsisFilterV2 dispatchRequest method: 
```
            // We can pass it only in case of GET request where no input stream is used
            if (HttpMethod.GET.name().equalsIgnoreCase(request.getMethod())) {
                passToFilters = true;
            } else {
                response.setStatus(HttpServletResponse.SC_NOT_FOUND);
            }
```
If we could allow an OPTIONS request to pass, then our preflight OPTIONS requests would go thru without an issue.

**Comment by meshuga** [comment]
Thanks for the issue!
I also added `HEAD` and `TRACE` as allowed methods

**Comment by keithdmoore** [comment]
Thanks for addressing is so quickly!

**Comment by etlweather** [comment]
@keithdmoore - would you be able to share how you got the `CorsFilter` to work?

**Comment by keithdmoore** [comment]
I created a custom filter in a Spring application but this approach would be better.
https://spring.io/guides/gs/rest-service-cors/.  You could define a global CORS configuration and then override it if necessary.

**Comment by etlweather** [comment]
Thanks for the fast answer - I tried the Spring `rest-service-cors` method and it did not work... but I just wrote a `Filter`.

**Comment by keithdmoore** [comment]
```java
@Configuration
public class CorsFilter extends OncePerRequestFilter {
    
    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response,
                    FilterChain filterChain) throws IOException, ServletException {

        response.setHeader("Access-Control-Allow-Origin", "*");
        response.setHeader("Access-Control-Allow-Methods", "POST, GET, OPTIONS, DELETE");
        response.setHeader("Access-Control-Max-Age", "3600");
        response.setHeader("Access-Control-Allow-Headers", "x-requested-with");
        filterChain.doFilter(request, response);
    }
}

```

**Comment by etlweather** [comment]
Thanks mate!
