### ISSUE TITLE
Path prefix is missing in relationship links

### ISSUE THREAD

**Issue by valimaggi** [katharsis-project/katharsis-spring#8]
When using Spring integration (i.e. KatharsisFilter in io.katharsis.spring package), I noticed that as the JSON responses from the backend are returned with those relationship links, these links don't have the katharsis.pathPrefix (defined in application.properties). So when I call the relationship in the frontend, the request URL to the backend is invalid (as it doesn't have that pathPrefix).

I noticed that in KatharsisFilter there is this createKatharsisInvokerContext which returns new ServletKatharsisInvokerContext which has some overridden methods in it. One of these methods is getRequestPath:

            public String getRequestPath() {
                String path = super.getRequestPath();

                if (pathPrefix != null && path.startsWith(pathPrefix)) {
                    path = path.substring(pathPrefix.length());
                }

                return path;
            }

We have our own class for filtering Katharsis request which extends KatharsisFilter class. There KatharsisFilter setPathPrefix method is called so in the above code pathPrefix variable has the value of our pathPrefix property.

Apparently this getRequestPath is called in several places as if I don't set that pathPrefix, I got some ResourceNotFound exception and if I set it, the relationship links in JSON don't have that pathPrefix (as its stripped in the above code).

How the KatharsisFilter is supposed to be used with Spring or is this a bug?

**UPDATE**  Did some digging and found out that getRequestPath has apparently nothing to do with creating the link URLs to responses. 

domainName is the property used when creating those link URLs, but is it used only in that purpose? Nevertheless, it could be better that the pathPrefix would be used in with the domainName when creating link URLs. Now it's a bit odd that I have to add that same pathPrefix also to the domainName property.

**Comment by collinpeters** [comment]
+1

**Comment by meshuga** [comment]
Fortunately, I started working with Katharsis + Spring, so I've made some refactoring - created a `KatharsisConfigV2` and `KatharsisFilterV2` which doesn't use katharsis-servlet Invoker and two additional inheritance layers in a filter, so the code is easier to read and more integrated with Spring :wink:
